### ISSUE TITLE
Criar links para os projetos

### ISSUE THREAD

**Issue by lesleyandrez** [douglasabnovato/douglasabnovato.dev#1]
Quando clicar em um card de um projeto do github, poderia direcionar para o readme do projeto.

<img width="1074" alt="Screen Shot 2022-03-17 at 19 43 12" src="https://user-images.githubusercontent.com/8854256/158906466-ca439adc-6499-4cef-aedd-4eb53ce2eb18.png">

**Comment by douglasabnovato** [comment]
linhas 17 a 20: links para a raiz de cada projeto dinamicamente
const a_repos = document.createElement('a')
a_repos.setAttribute('href', repository.html_url)
a_repos.setAttribute('target', '_blank')
a_repos.setAttribute('rel', 'noopener')
